.PHONY: clean all

cc=gcc

all:libwpa_cli_wrapper.a libwpa_cli_wrapper_test

libwpa_cli_wrapper.a:
	rm libwpa_cli_wrapper.o -f 
	rm libwpa_cli_wrapper.a -f 
	make -f Makefile libwpa_cli_wrapper.a
	
libwpa_cli_wrapper_test:libwpa_cli_wrapper_test.c
	${cc} libwpa_cli_wrapper_test.c -o libwpa_cli_wrapper_test -lwpa_cli_wrapper -L.

clean:
	rm libwpa_cli_wrapper.o -f
	rm libwpa_cli_wrapper.a -f
	rm libwpa_cli_wrapper_test -f 
