.PHONY: clean all

cc=gcc

LIB=libwpa_cli_wrapper.a

BIN= libwpa_cli_wrapper_test

all:${LIB} ${BIN} 

${LIB}:libwpa_cli_wrapper.c
	rm libwpa_cli_wrapper.o -f 
	rm libwpa_cli_wrapper.a -f 
	make -f Makefile ${LIB}
	
${BIN}:libwpa_cli_wrapper_test.c
	${cc} libwpa_cli_wrapper_test.c -o ${BIN} -lwpa_cli_wrapper -L.

clean:
	rm libwpa_cli_wrapper.o -f
	rm ${LIB} -f
	rm ${BIN} -f 
